# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 429204a3dbde842377d390df36e1b370f5adb83ce434878282b61bcf5f17f0a37bbc730f51af4eceb08e9977a6ba9d0065604ed4b0ec9fc3b3d4846f2df92a89

test:
  secret_key_base: 7e95bdc9a245df90380d6dda5a8017c49a378d4641b93651795cb088f53239c7b621ee119ed5ba9f121a5dfd4b6da3dd585fd7976ddc82d92fe9a1bceb65e9da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
